/**
 * Database Schema Types
 * These types represent the structure of data stored in Supabase
 * Table names and column names use snake_case to match PostgreSQL conventions
 */

import type { DerivedMetrics, AIInsights } from './application.ts';
import type { ChampionStats, ProPlayerProfile } from './application.ts';

// ==================== PLAYERS TABLE ====================

/**
 * players table schema
 * Stores analyzed player data and insights
 */
export interface DBPlayer {
  // Primary key
  puuid: string;

  // Player identity (from Riot Account API)
  riot_id: string;
  tag_line: string;
  region: string;

  // Basic stats (aggregated from matches)
  total_games: number;
  wins: number;
  losses: number;
  win_rate: number;

  // Champion & role data (JSON columns)
  main_role: string;
  top_champions: ChampionStats[]; // JSONB array
  champion_pool_size: number;

  // Performance averages
  avg_kda: number;
  avg_kills: number;
  avg_deaths: number;
  avg_assists: number;
  avg_cs: number;
  avg_vision_score: number;
  avg_game_duration: number;

  // Streaks
  longest_win_streak: number;
  longest_loss_streak: number;
  current_streak_type: 'win' | 'loss' | null;
  current_streak_length: number;

  narrative_story: string | null;
  // Advanced analytics (JSONB columns)
  derived_metrics: DerivedMetrics; // All calculated metrics
  insights: AIInsights; // AI-generated insights
  archetype: string; // Player archetype name

  // Pro comparison (JSONB column)
  pro_comparison: {
    primary: ProPlayerProfile;
    secondary: ProPlayerProfile;
    similarity: number;
    description: string;
  } | null;

  // Strengths/weaknesses (JSONB columns)
  top_strengths: Array<{
    metric: string;
    value: number;
    percentile: number;
  }> | null;
  needs_work: Array<{
    metric: string;
    value: number;
    suggestion: string;
  }> | null;

  playful_comparison: string | null;

  // Metadata
  generated_at: string; // ISO timestamp
  created_at?: string; // Auto-generated by DB
  updated_at?: string; // Auto-generated by DB
}

// ==================== MATCHES TABLE ====================

/**
 * matches table schema
 * Stores individual match data for players
 */
export interface DBMatch {
  // Composite primary key (match_id + puuid)
  match_id: string;
  puuid: string; // Foreign key to players

  // Match metadata
  game_date: string; // ISO timestamp
  game_duration: number; // seconds
  queue_id: number;

  // Champion & position
  champion_id: number;
  champion_name: string;
  role: string; // TOP, JUNGLE, MID, ADC, SUPPORT

  // Match outcome
  result: boolean; // true = win, false = loss
  team_id: number;

  // Core stats
  kills: number;
  deaths: number;
  assists: number;
  kda: number;

  // Economic stats
  gold: number;
  cs: number; // totalMinionsKilled + neutralMinionsKilled

  // Combat stats
  damage_dealt: number; // totalDamageDealtToChampions
  damage_taken: number;

  // Vision stats
  vision_score: number;
  wards_placed: number;
  wards_destroyed: number;

  // Calculated metrics
  performance_score: number; // 0-100 calculated score
  is_watershed: boolean; // Marks watershed moments

  // Items (for reference)
  items: number[]; // Array of item IDs [item0, item1, ..., item6]

  // Metadata
  created_at?: string; // Auto-generated by DB
}

// ==================== ANALYSIS_CACHE TABLE ====================

/**
 * analysis_cache table schema
 * Tracks when players were last analyzed to avoid redundant API calls
 */
export interface DBAnalysisCache {
  puuid: string; // Primary key, foreign key to players
  last_analyzed: string; // ISO timestamp
  needs_refresh: boolean;
  match_count: number; // Number of matches analyzed
  created_at?: string;
  updated_at?: string;
}

// ==================== FRIEND_GROUPS TABLE ====================

/**
 * friend_groups table schema
 * Stores friend group metadata
 */
export interface DBFriendGroup {
  id: string; // UUID primary key
  name: string;
  created_by: string | null; // PUUID of creator (optional)

  // Group dynamics (JSONB)
  dynamics: {
    best_duo?: {
      player1_puuid: string;
      player2_puuid: string;
      win_rate: number;
      games_played: number;
    };
    mvp?: {
      puuid: string;
      riot_id: string;
      avg_performance: number;
    };
    tilt_chains?: Array<{
      trigger: string; // PUUID
      affected: string; // PUUID
      correlation: number; // 0-1
    }>;
  } | null;

  created_at?: string;
  updated_at?: string;
}

// ==================== FRIEND_GROUP_MEMBERS TABLE ====================

/**
 * friend_group_members table schema
 * Junction table for friend groups and players (many-to-many)
 */
export interface DBFriendGroupMember {
  group_id: string; // Foreign key to friend_groups
  puuid: string; // Foreign key to players
  joined_at?: string;
}

// ==================== SHARE_CARDS TABLE ====================

/**
 * share_cards table schema
 * Stores generated share cards and metadata for sharing flows
 */
export interface DBShareCard {
  id: string;
  slug: string;
  player_puuid: string | null;
  player_riot_id: string | null;
  player_tag_line: string | null;
  caption: string | null;
  image_path: string;
  player_snapshot: Record<string, unknown> | null;
  download_count: number;
  last_shared_at: string | null;
  expires_at: string | null;
  created_at?: string;
  updated_at?: string;
}

export interface DBShareCardInsert {
  slug: string;
  player_puuid?: string | null;
  player_riot_id?: string | null;
  player_tag_line?: string | null;
  caption?: string | null;
  image_path: string;
  player_snapshot?: Record<string, unknown> | null;
  expires_at?: string | null;
}

// ==================== PERFORMANCE_TRENDS TABLE ====================

/**
 * performance_trends table schema (optional)
 * Pre-calculated performance trends for faster loading
 */
export interface DBPerformanceTrend {
  puuid: string; // Foreign key to players
  date: string; // ISO date (YYYY-MM-DD)
  week_number: number; // Week of year

  // Aggregated stats for this time period
  performance_score: number;
  win_rate: number;
  games_played: number;
  avg_kda: number;

  created_at?: string;
}

// ==================== HELPER TYPES ====================

/**
 * Type for database insert operations (excludes auto-generated fields)
 */
export type DBPlayerInsert = Omit<DBPlayer, 'created_at' | 'updated_at'>;
export type DBMatchInsert = Omit<DBMatch, 'created_at'>;
export type DBAnalysisCacheInsert = Omit<DBAnalysisCache, 'created_at' | 'updated_at'>;
export type DBFriendGroupInsert = Omit<DBFriendGroup, 'id' | 'created_at' | 'updated_at'>;

/**
 * Type for database update operations (all fields optional except primary key)
 */
export type DBPlayerUpdate = Partial<DBPlayer> & { puuid: string };
export type DBMatchUpdate = Partial<DBMatch> & { match_id: string; puuid: string };
export type DBAnalysisCacheUpdate = Partial<DBAnalysisCache> & { puuid: string };
