import type { ArchetypeProfile } from '../types/index.ts';
// ==================== ARCHETYPE DEFINITIONS ====================

export const ARCHETYPES: ArchetypeProfile[] = [
  {
    name: 'Calculated Assassin',
    description: 'High aggression with surgical precision. Knows when to strike.',
    profile: {
      aggression: 85,
      consistency: 70,
      clutchFactor: 80,
      farming: 60,
      vision: 50,
      earlyGameStrength: 75,
      lateGameScaling: 65,
    },
    icon: '🗡️',
  },
  {
    name: 'Scaling Specialist',
    description: 'Patient farmer who dominates late game. Weak early, unstoppable late.',
    profile: {
      farming: 90,
      lateGameScaling: 85,
      earlyGameStrength: 40,
      consistency: 80,
      aggression: 35,
      vision: 65,
      clutchFactor: 70,
    },
    icon: '📈',
  },
  {
    name: 'Vision Mastermind',
    description: 'Eyes everywhere. Controls the map with superior vision and information.',
    profile: {
      vision: 95,
      roaming: 70,
      teamfighting: 75,
      aggression: 50,
      farming: 60,
      consistency: 75,
      earlyGameStrength: 60,
    },
    icon: '👁️',
  },
  {
    name: 'Teamfight Commander',
    description: 'Thrives in chaos. The bigger the fight, the better they perform.',
    profile: {
      teamfighting: 90,
      clutchFactor: 85,
      aggression: 70,
      vision: 65,
      consistency: 75,
      lateGameScaling: 80,
      earlyGameStrength: 60,
    },
    icon: '⚔️',
  },
  {
    name: 'Early Game Bully',
    description: 'Dominates the first 15 minutes. Snowballs leads to victory.',
    profile: {
      earlyGameStrength: 95,
      aggression: 85,
      snowballRate: 80,
      lateGameScaling: 40,
      vision: 50,
      farming: 65,
      consistency: 60,
    },
    icon: '💪',
  },
  {
    name: 'Consistent Performer',
    description: 'Reliable and steady. Never ints, always contributes.',
    profile: {
      consistency: 95,
      tiltFactor: 20,
      aggression: 55,
      farming: 75,
      vision: 70,
      earlyGameStrength: 60,
      lateGameScaling: 60,
    },
    icon: '🎯',
  },
  {
    name: 'Clutch Player',
    description: 'Performs best under pressure. Turns impossible games around.',
    profile: {
      clutchFactor: 95,
      comebackRate: 85,
      aggression: 75,
      teamfighting: 80,
      consistency: 65,
      earlyGameStrength: 60,
      lateGameScaling: 70,
    },
    icon: '🔥',
  },
  {
    name: 'CS God',
    description: 'Farming perfection. Highest CS/min in every game.',
    profile: {
      farming: 95,
      consistency: 85,
      aggression: 40,
      vision: 55,
      earlyGameStrength: 60,
      lateGameScaling: 80,
      clutchFactor: 60,
    },
    icon: '💰',
  },
  {
    name: 'Roaming Terror',
    description: 'Never stays in lane. Creates pressure across the entire map.',
    profile: {
      roaming: 95,
      aggression: 80,
      vision: 75,
      farming: 50,
      earlyGameStrength: 80,
      teamfighting: 70,
      consistency: 60,
    },
    icon: '🌪️',
  },
  {
    name: 'Comeback King',
    description: 'Best when behind. Specializes in turning lost games into wins.',
    profile: {
      comebackRate: 90,
      clutchFactor: 85,
      lateGameScaling: 80,
      tiltFactor: 30,
      consistency: 70,
      teamfighting: 75,
      aggression: 65,
    },
    icon: '👑',
  },
  {
    name: 'Tilt-Proof Machine',
    description: 'Unshakeable mental. Performance never drops after losses.',
    profile: {
      tiltFactor: 10,
      consistency: 90,
      clutchFactor: 75,
      aggression: 60,
      farming: 70,
      vision: 70,
      earlyGameStrength: 60,
    },
    icon: '🧘',
  },
  {
    name: 'Snowball Expert',
    description: 'Gets ahead early and never lets go. Chokes out opponents.',
    profile: {
      snowballRate: 95,
      earlyGameStrength: 85,
      aggression: 80,
      farming: 70,
      lateGameScaling: 55,
      consistency: 70,
      clutchFactor: 65,
    },
    icon: '❄️',
  },
  {
    name: 'Safe Scaler',
    description: 'Plays safe, farms well, scales hard. Avoids risks.',
    profile: {
      farming: 85,
      consistency: 85,
      lateGameScaling: 85,
      aggression: 30,
      earlyGameStrength: 40,
      tiltFactor: 40,
      vision: 60,
    },
    icon: '🛡️',
  },
  {
    name: 'Chaos Agent',
    description: 'High variance, high reward. Either pops off or ints.',
    profile: {
      aggression: 95,
      consistency: 30,
      clutchFactor: 80,
      earlyGameStrength: 85,
      tiltFactor: 70,
      farming: 50,
      vision: 45,
    },
    icon: '🎲',
  },
  {
    name: 'Balanced Tactician',
    description: 'Well-rounded in all aspects. Master of fundamentals.',
    profile: {
      aggression: 65,
      farming: 70,
      vision: 70,
      consistency: 75,
      earlyGameStrength: 65,
      lateGameScaling: 65,
      clutchFactor: 70,
    },
    icon: '⚖️',
  },
];