/**
 * Professional player profile from Worlds 2024
 */
export interface ProPlayerProfile {
  name: string;
  team: string;
  role: 'Top' | 'Jungle' | 'Mid' | 'ADC' | 'Support';
  region: 'LCK' | 'LPL' | 'LEC' | 'LCS' | 'PCS' | 'VCS';
  playstyle: string;
  metrics: Partial<DerivedMetrics>;
  achievements?: string;
  icon: string;
}

// ==================== PRO PLAYER PROFILES ====================

/**
 * Worlds 2024 professional player profiles
 * Metrics estimated from professional analysis and statistics
 */
export const WORLDS_2024_PRO_PLAYERS: ProPlayerProfile[] = [
  // ==================== T1 (WORLDS 2024 CHAMPIONS) ====================
  {
    name: 'Faker',
    team: 'T1',
    role: 'Mid',
    region: 'LCK',
    playstyle: 'The Unkillable Demon King - Clutch playmaker with legendary status',
    metrics: {
      clutchFactor: 98,
      consistency: 92,
      aggression: 85,
      teamfighting: 90,
      lateGameScaling: 85,
      roaming: 82,
      comebackRate: 95,
    },
    achievements: '5x Worlds Champion (2024 MVP)',
    icon: '🇰🇷',
  },
  {
    name: 'Zeus',
    team: 'T1', // Left to HLE after Worlds 2024
    role: 'Top',
    region: 'LCK',
    playstyle: 'Dominant lane carry with exceptional snowball potential',
    metrics: {
      earlyGameStrength: 95,
      aggression: 92,
      snowballRate: 90,
      consistency: 88,
      teamfighting: 85,
      lateGameScaling: 80,
      clutchFactor: 87,
    },
    achievements: 'Worlds 2024 Champion',
    icon: '🇰🇷',
  },
  {
    name: 'Oner',
    team: 'T1',
    role: 'Jungle',
    region: 'LCK',
    playstyle: 'Aggressive jungler with perfect objective control',
    metrics: {
      aggression: 88,
      roaming: 92,
      earlyGameStrength: 90,
      vision: 85,
      consistency: 87,
      clutchFactor: 88,
      snowballRate: 85,
    },
    achievements: 'Worlds 2024 Champion',
    icon: '🇰🇷',
  },
  {
    name: 'Gumayusi',
    team: 'T1',
    role: 'ADC',
    region: 'LCK',
    playstyle: 'High-variance mechanical genius with clutch teamfighting',
    metrics: {
      clutchFactor: 92,
      aggression: 88,
      teamfighting: 93,
      consistency: 75,
      lateGameScaling: 88,
      farming: 90,
      earlyGameStrength: 82,
    },
    achievements: 'Worlds 2024 Champion',
    icon: '🇰🇷',
  },
  {
    name: 'Keria',
    team: 'T1',
    role: 'Support',
    region: 'LCK',
    playstyle: 'Vision mastermind and aggressive playmaking support',
    metrics: {
      vision: 98,
      roaming: 93,
      aggression: 88,
      clutchFactor: 90,
      teamfighting: 95,
      consistency: 90,
      earlyGameStrength: 88,
    },
    achievements: 'Worlds 2024 Champion',
    icon: '🇰🇷',
  },

  // ==================== BLG (WORLDS 2024 RUNNERS-UP) ====================
  {
    name: 'Bin',
    team: 'BLG',
    role: 'Top',
    region: 'LPL',
    playstyle: 'High-risk, high-reward Jax master with extreme variance',
    metrics: {
      aggression: 96,
      clutchFactor: 88,
      earlyGameStrength: 92,
      consistency: 55,
      snowballRate: 90,
      teamfighting: 85,
      lateGameScaling: 75,
    },
    achievements: 'Worlds 2024 Finalist, LPL Champion',
    icon: '🇨🇳',
  },
  {
    name: 'Xun',
    team: 'BLG',
    role: 'Jungle',
    region: 'LPL',
    playstyle: 'Aggressive jungler with strong early game pressure',
    metrics: {
      aggression: 90,
      earlyGameStrength: 92,
      roaming: 88,
      vision: 80,
      snowballRate: 87,
      consistency: 80,
      clutchFactor: 82,
    },
    achievements: 'Worlds 2024 Finalist',
    icon: '🇨🇳',
  },
  {
    name: 'Knight',
    team: 'BLG',
    role: 'Mid',
    region: 'LPL',
    playstyle: 'Consistent DPS machine with exceptional teamfighting',
    metrics: {
      teamfighting: 96,
      consistency: 94,
      farming: 92,
      lateGameScaling: 90,
      clutchFactor: 88,
      aggression: 78,
      earlyGameStrength: 82,
    },
    achievements: 'Worlds 2024 Finalist, LPL MVP',
    icon: '🇨🇳',
  },
  {
    name: 'Elk',
    team: 'BLG',
    role: 'ADC',
    region: 'LPL',
    playstyle: 'Aggressive lane-dominant ADC with strong positioning',
    metrics: {
      aggression: 90,
      earlyGameStrength: 88,
      teamfighting: 92,
      consistency: 85,
      lateGameScaling: 85,
      farming: 88,
      clutchFactor: 85,
    },
    achievements: 'Worlds 2024 Finalist',
    icon: '🇨🇳',
  },
  {
    name: 'ON',
    team: 'BLG',
    role: 'Support',
    region: 'LPL',
    playstyle: 'Aggressive roaming support with strong engage',
    metrics: {
      roaming: 94,
      aggression: 90,
      vision: 82,
      clutchFactor: 85,
      teamfighting: 88,
      earlyGameStrength: 88,
      consistency: 80,
    },
    achievements: 'Worlds 2024 Finalist',
    icon: '🇨🇳',
  },

  // ==================== GEN.G (SEMIFINALS) ====================
  {
    name: 'Chovy',
    team: 'Gen.G',
    role: 'Mid',
    region: 'LCK',
    playstyle: 'Perfect CS machine with exceptional scaling',
    metrics: {
      farming: 99,
      consistency: 96,
      lateGameScaling: 92,
      teamfighting: 90,
      aggression: 65,
      clutchFactor: 87,
      earlyGameStrength: 75,
    },
    achievements: 'MSI 2024 Champion, LCK MVP',
    icon: '🇰🇷',
  },
  {
    name: 'Peyz',
    team: 'Gen.G',
    role: 'ADC',
    region: 'LCK',
    playstyle: 'Rising star ADC with aggressive teamfighting',
    metrics: {
      aggression: 88,
      teamfighting: 90,
      earlyGameStrength: 87,
      lateGameScaling: 85,
      consistency: 83,
      clutchFactor: 85,
      farming: 88,
    },
    achievements: 'MSI 2024 Champion',
    icon: '🇰🇷',
  },
  {
    name: 'Canyon',
    team: 'Gen.G',
    role: 'Jungle',
    region: 'LCK',
    playstyle: 'Cerebral jungler with perfect pathing and vision control',
    metrics: {
      vision: 95,
      consistency: 94,
      roaming: 90,
      earlyGameStrength: 88,
      clutchFactor: 90,
      teamfighting: 88,
      aggression: 80,
    },
    achievements: 'MSI 2024 Champion, Worlds 2020 Champion',
    icon: '🇰🇷',
  },

  // ==================== HLE (HANWHA LIFE ESPORTS - SEMIFINALS) ====================
  {
    name: 'Doran',
    team: 'HLE',
    role: 'Top',
    region: 'LCK',
    playstyle: 'Versatile top with strong teamfighting and reliability',
    metrics: {
      teamfighting: 90,
      consistency: 87,
      lateGameScaling: 85,
      farming: 85,
      earlyGameStrength: 80,
      aggression: 75,
      clutchFactor: 82,
    },
    achievements: 'Worlds 2024 Semifinalist',
    icon: '🇰🇷',
  },
  {
    name: 'Zeka',
    team: 'HLE',
    role: 'Mid',
    region: 'LCK',
    playstyle: 'Clutch performer who thrives under pressure',
    metrics: {
      clutchFactor: 94,
      teamfighting: 89,
      consistency: 82,
      aggression: 80,
      lateGameScaling: 85,
      comebackRate: 88,
      farming: 83,
    },
    achievements: 'Worlds 2022 Champion',
    icon: '🇰🇷',
  },
  {
    name: 'Viper',
    team: 'HLE',
    role: 'ADC',
    region: 'LCK',
    playstyle: 'Consistent ADC with exceptional positioning',
    metrics: {
      consistency: 93,
      teamfighting: 92,
      lateGameScaling: 90,
      farming: 92,
      clutchFactor: 88,
      aggression: 70,
      earlyGameStrength: 78,
    },
    achievements: 'Worlds 2021 Champion',
    icon: '🇰🇷',
  },

  // ==================== WEIBO GAMING (QUARTERFINALS) ====================
  {
    name: 'TheShy',
    team: 'Weibo Gaming',
    role: 'Top',
    region: 'LPL',
    playstyle: 'Legendary aggressive carry with high variance',
    metrics: {
      aggression: 97,
      clutchFactor: 88,
      earlyGameStrength: 93,
      consistency: 60,
      snowballRate: 92,
      lateGameScaling: 75,
      teamfighting: 82,
    },
    achievements: 'Worlds 2018 Champion',
    icon: '🇨🇳',
  },
  {
    name: 'Xiaohu',
    team: 'Weibo Gaming',
    role: 'Mid',
    region: 'LPL',
    playstyle: 'Versatile veteran with deep champion pool',
    metrics: {
      championPoolDepth: 94,
      consistency: 90,
      teamfighting: 88,
      farming: 85,
      lateGameScaling: 87,
      clutchFactor: 87,
      earlyGameStrength: 78,
    },
    achievements: 'MSI 2021 Champion',
    icon: '🇨🇳',
  },

  // ==================== TOP ESPORTS (SWISS STAGE) ====================
  {
    name: 'JackeyLove',
    team: 'Top Esports',
    role: 'ADC',
    region: 'LPL',
    playstyle: 'Aggressive lane dominant ADC with clutch potential',
    metrics: {
      aggression: 92,
      clutchFactor: 90,
      earlyGameStrength: 90,
      teamfighting: 90,
      consistency: 78,
      lateGameScaling: 85,
      farming: 88,
    },
    achievements: 'Worlds 2019 Champion',
    icon: '🇨🇳',
  },
  {
    name: '369',
    team: 'Top Esports',
    role: 'Top',
    region: 'LPL',
    playstyle: 'Reliable carry top with strong teamfighting',
    metrics: {
      consistency: 90,
      teamfighting: 90,
      lateGameScaling: 88,
      farming: 88,
      snowballRate: 85,
      earlyGameStrength: 83,
      aggression: 80,
    },
    achievements: 'LPL Champion',
    icon: '🇨🇳',
  },

  // ==================== G2 ESPORTS (QUARTERFINALS) ====================
  {
    name: 'Caps',
    team: 'G2 Esports',
    role: 'Mid',
    region: 'LEC',
    playstyle: 'Baby Faker - High-risk playmaker with explosive potential',
    metrics: {
      aggression: 94,
      clutchFactor: 90,
      consistency: 68,
      roaming: 88,
      earlyGameStrength: 85,
      teamfighting: 85,
      comebackRate: 85,
    },
    achievements: 'MSI 2019 Champion, 4x LEC Champion',
    icon: '🇪🇺',
  },
  {
    name: 'Hans Sama',
    team: 'G2 Esports',
    role: 'ADC',
    region: 'LEC',
    playstyle: 'Aggressive ADC who thrives in skirmishes',
    metrics: {
      aggression: 87,
      teamfighting: 88,
      earlyGameStrength: 83,
      consistency: 82,
      lateGameScaling: 83,
      clutchFactor: 83,
      farming: 84,
    },
    achievements: 'Worlds 2024 Quarterfinalist',
    icon: '🇪🇺',
  },
  {
    name: 'Yike',
    team: 'G2 Esports',
    role: 'Jungle',
    region: 'LEC',
    playstyle: 'Aggressive early-game jungler with smart pathing',
    metrics: {
      earlyGameStrength: 90,
      aggression: 88,
      roaming: 88,
      vision: 82,
      consistency: 80,
      snowballRate: 85,
      teamfighting: 82,
    },
    achievements: 'LEC Champion 2024',
    icon: '🇪🇺',
  },

  // ==================== FLYQUEST (QUARTERFINALS) ====================
  {
    name: 'Bwipo',
    team: 'FlyQuest',
    role: 'Top',
    region: 'LCS',
    playstyle: 'Versatile veteran with champion pool depth',
    metrics: {
      championPoolDepth: 90,
      consistency: 85,
      aggression: 82,
      teamfighting: 87,
      clutchFactor: 85,
      earlyGameStrength: 80,
      lateGameScaling: 78,
    },
    achievements: 'Worlds 2018 Finalist, LCS Champion',
    icon: '🇺🇸',
  },
  {
    name: 'Inspired',
    team: 'FlyQuest',
    role: 'Jungle',
    region: 'LCS',
    playstyle: 'Smart pathing and vision control specialist',
    metrics: {
      vision: 92,
      consistency: 88,
      roaming: 87,
      earlyGameStrength: 85,
      clutchFactor: 82,
      teamfighting: 85,
      aggression: 78,
    },
    achievements: 'LCS Champion, LEC MVP',
    icon: '🇺🇸',
  },

  // ==================== TEAM LIQUID (SWISS STAGE) ====================
  {
    name: 'Impact',
    team: 'Team Liquid',
    role: 'Top',
    region: 'LCS',
    playstyle: 'Rock-solid veteran with exceptional consistency',
    metrics: {
      consistency: 94,
      teamfighting: 90,
      lateGameScaling: 88,
      tiltFactor: 15,
      clutchFactor: 90,
      farming: 85,
      earlyGameStrength: 78,
    },
    achievements: 'Worlds 2013 Champion',
    icon: '🇺🇸',
  },
  {
    name: 'CoreJJ',
    team: 'Team Liquid',
    role: 'Support',
    region: 'LCS',
    playstyle: 'World-class support with vision mastery',
    metrics: {
      vision: 96,
      consistency: 92,
      teamfighting: 92,
      clutchFactor: 88,
      roaming: 85,
      earlyGameStrength: 82,
      aggression: 75,
    },
    achievements: 'Worlds 2017 Champion',
    icon: '🇺🇸',
  },

  // ==================== DPLUS KIA (SWISS STAGE) ====================
  {
    name: 'ShowMaker',
    team: 'Dplus KIA',
    role: 'Mid',
    region: 'LCK',
    playstyle: 'Clutch mechanical genius with lane dominance',
    metrics: {
      clutchFactor: 92,
      aggression: 88,
      consistency: 88,
      teamfighting: 90,
      earlyGameStrength: 87,
      lateGameScaling: 85,
      farming: 88,
    },
    achievements: 'Worlds 2020 Champion',
    icon: '🇰🇷',
  },
  {
    name: 'Deft',
    team: 'Dplus KIA',
    role: 'ADC',
    region: 'LCK',
    playstyle: 'Legendary ADC with patient scaling',
    metrics: {
      lateGameScaling: 94,
      consistency: 92,
      teamfighting: 93,
      farming: 93,
      clutchFactor: 90,
      aggression: 70,
      earlyGameStrength: 75,
    },
    achievements: 'Worlds 2022 Champion',
    icon: '🇰🇷',
  },

  // ==================== LNG ESPORTS (SWISS STAGE) ====================
  {
    name: 'Tarzan',
    team: 'LNG Esports',
    role: 'Jungle',
    region: 'LPL',
    playstyle: 'Cerebral jungler with perfect macro play',
    metrics: {
      vision: 93,
      consistency: 90,
      roaming: 90,
      clutchFactor: 87,
      earlyGameStrength: 87,
      teamfighting: 88,
      aggression: 82,
    },
    achievements: 'LPL Champion',
    icon: '🇨🇳',
  },
  {
    name: 'Gala',
    team: 'LNG Esports',
    role: 'ADC',
    region: 'LPL',
    playstyle: 'Consistent teamfight ADC with strong positioning',
    metrics: {
      teamfighting: 92,
      consistency: 90,
      lateGameScaling: 90,
      farming: 90,
      clutchFactor: 87,
      aggression: 75,
      earlyGameStrength: 80,
    },
    achievements: 'MSI 2021 Finalist',
    icon: '🇨🇳',
  },

  // ==================== FNATIC (SWISS STAGE) ====================
  {
    name: 'Razork',
    team: 'Fnatic',
    role: 'Jungle',
    region: 'LEC',
    playstyle: 'Aggressive early-game jungler',
    metrics: {
      aggression: 88,
      earlyGameStrength: 88,
      roaming: 85,
      snowballRate: 83,
      consistency: 78,
      vision: 80,
      teamfighting: 80,
    },
    achievements: 'LEC Champion',
    icon: '🇪🇺',
  },
  {
    name: 'Humanoid',
    team: 'Fnatic',
    role: 'Mid',
    region: 'LEC',
    playstyle: 'Lane-dominant mid with strong roaming',
    metrics: {
      aggression: 85,
      roaming: 85,
      earlyGameStrength: 85,
      consistency: 82,
      teamfighting: 85,
      lateGameScaling: 80,
      clutchFactor: 82,
    },
    achievements: 'LEC Champion',
    icon: '🇪🇺',
  },
];